# CDK20_HUMAN: 相同蛋白の探索と既知活性化合物の収集

CDK20_HUMANはまだX線結晶構造が解かれていない。そこで、

1. CDK20自体の既知の活性化合物をChEMBLから収集する
2. UniProt/BLASTでCDK20に配列が近い蛋白を探す
3. 見つかった蛋白ごとにPDBエントリ数・ChEMBL活性化合物数を集計し、この研究で参照蛋白として活用できそうなものをランキングする

In [1]:
from pathlib import Path

TARGET = "CDK20_HUMAN"
OUTDIR = Path("data/cdk20_investigation")
OUTDIR.mkdir(parents=True, exist_ok=True)

# ChEMBL Web APIが障害等で使えない場合のフォールバック(ChEMBL公式配布のSQLite)
CHEMBL_DB = Path("data/chembl/chembl_36.db")

In [2]:
from idmap import resolve_uniprot_accession

accession = resolve_uniprot_accession(TARGET)
print(accession)

12:32:37 [idmap.identifiers] Resolving UniProt entry name CDK20_HUMAN -> accession ...
12:32:38 [idmap.identifiers]   -> Q8IZL9

Q8IZL9

## 1. CDK20自体の既知活性化合物を収集(ChEMBL)

構造とは独立に、CDK20_HUMANに対する既知の活性化合物(pChEMBL値あり)をChEMBLから取得する。

In [3]:
import pandas as pd
from chembl import local as chembl_local

chembl_target_id = chembl_local.resolve_target_chembl_id(accession, CHEMBL_DB)
activities = chembl_local.fetch_activities(chembl_target_id, CHEMBL_DB)

compounds_df = pd.DataFrame(activities)
if not compounds_df.empty:
    compounds_df = compounds_df[
        ["molecule_chembl_id", "molecule_pref_name", "canonical_smiles",
         "standard_type", "standard_value", "standard_units", "pchembl_value",
         "assay_chembl_id", "document_chembl_id"]
    ].sort_values("pchembl_value", ascending=False).reset_index(drop=True)
compounds_df.to_csv(OUTDIR / "known_compounds.csv", index=False)
compounds_df

12:32:46 [chembl.local] Resolving UniProt accession Q8IZL9 -> ChEMBL target id (local DB) ...
12:32:46 [chembl.local]   -> CHEMBL3559690
12:32:46 [chembl.local] Fetching activities for target CHEMBL3559690 (pChEMBL value required, local DB) ...
12:32:46 [chembl.local]   -> 1 activities fetched for CHEMBL3559690

,molecule_chembl_id,molecule_pref_name,canonical_smiles,standard_type,standard_value,standard_units,pchembl_value,assay_chembl_id,document_chembl_id
0,CHEMBL4445812,None,O=C(Nc1ccc2cc(C(=O)Nc3nccs3)ccc2c1)c1ccc(Cl)c(...,Kd,8020,nM,5.1,CHEMBL4375310,CHEMBL4373706

In [4]:
from uniprot.entry import fetch_fasta

fasta = fetch_fasta(accession).decode()
sequence = "".join(line for line in fasta.splitlines() if not line.startswith(">"))
print(fasta)
print(f"sequence length: {len(sequence)}")

12:32:48 [uniprot.entry] Fetching UniProt FASTA for Q8IZL9 ...

>sp|Q8IZL9|CDK20_HUMAN Cyclin-dependent kinase 20 OS=Homo sapiens OX=9606 GN=CDK20 PE=1 SV=1
MDQYCILGRIGEGAHGIVFKAKHVETGEIVALKKVALRRLEDGFPNQALREIKALQEMED
NQYVVQLKAVFPHGGGFVLAFEFMLSDLAEVVRHAQRPLAQAQVKSYLQMLLKGVAFCHA
NNIVHRDLKPANLLISASGQLKIADFGLARVFSPDGSRLYTHQVATRWYRAPELLYGARQ
YDQGVDLWSVGCIMGELLNGSPLFPGKNDIEQLCYVLRILGTPNPQVWPELTELPDYNKI
SFKEQVPMPLEEVLPDVSPQALDLLGQFLLYPPHQRIAASKALLHQYFFTAPLPAHPSEL
PIPQRLGGPAPKAHPGPPHIHDFHVDRPLEESLLNPELIRPFILEG

sequence length: 346

## 2. UniProt/BLASTでCDK20に近い蛋白を探す

swissprot(UniProtKB/Swiss-Prot、審査済みエントリ)データベースに対し、Homo sapiensに限定してBLASTサーチを行い、
CDK20_HUMANに配列が近い蛋白(UniProt accession)を集める。配列同一性(identity)が40%を割る蛋白は
遠縁とみなし対象から除外する。

In [5]:
import pickle
from blastsearch import fetch_hits, submit_blast, wait_for_blast

HITS_CACHE = OUTDIR / "blast_hits.pkl"
RID_CACHE = OUTDIR / "blast_rid.txt"

if HITS_CACHE.exists():
    print(f"Using cached BLAST hits: {HITS_CACHE}")
    with open(HITS_CACHE, "rb") as f:
        hits = pickle.load(f)
else:
    if RID_CACHE.exists():
        rid = RID_CACHE.read_text().strip()
        print(f"Resuming existing BLAST job {rid} (submitted previously) ...")
    else:
        rid = submit_blast(sequence, program="blastp", database="swissprot", entrez_query="Homo sapiens[Organism]")
        RID_CACHE.write_text(rid)

    try:
        wait_for_blast(rid, poll_interval=10.0, timeout=600.0)
    except RuntimeError:
        # ジョブ自体が失敗した場合は再投函が必要なのでRIDキャッシュを破棄する
        RID_CACHE.unlink(missing_ok=True)
        raise
    # TimeoutErrorはRID_CACHEを残したまま伝播させる(セルを再実行すれば同じRIDで待機を再開できる)

    hits = fetch_hits(rid)
    with open(HITS_CACHE, "wb") as f:
        pickle.dump(hits, f)
    RID_CACHE.unlink(missing_ok=True)
    print(f"Saved BLAST hits to {HITS_CACHE}")

Using cached BLAST hits: data/cdk20_investigation/blast_hits.pkl

In [6]:
import pandas as pd
from blastsearch import parse_uniprot_subject_id
from uniprot.entry import fetch_entry_names

# UniProt accessionごとに最良ヒット(evalue最小)だけを残す。CDK20_HUMAN自身は除く。
best_by_accession = {}
for h in hits:
    acc = parse_uniprot_subject_id(h["subject_id"])
    if acc == accession:
        continue
    if acc not in best_by_accession or h["evalue"] < best_by_accession[acc]["evalue"]:
        best_by_accession[acc] = {**h, "accession": acc}
unique_hits = sorted(best_by_accession.values(), key=lambda h: h["evalue"])

hits_df = pd.DataFrame(unique_hits)

IDENTITY_MIN = 40.0
hits_df = hits_df[hits_df["identity"] >= IDENTITY_MIN].reset_index(drop=True)

entry_names = fetch_entry_names(hits_df["accession"].tolist())
hits_df["entry_name"] = hits_df["accession"].map(entry_names)
hits_df["coverage"] = (hits_df["align_length"] / len(sequence) * 100).round(1)
hits_df = hits_df[["accession", "entry_name", "identity", "coverage", "align_length", "evalue", "bit_score"]]
hits_df.to_csv(OUTDIR / "blast_hits.csv", index=False)
print(f"unique candidate proteins (identity >= {IDENTITY_MIN}%): {len(hits_df)}")


def _format_evalue(e: float) -> str:
    """0はそのまま「0」、それ以外は有効数字2桁の指数表記(例: 9.47e-95 -> 9.5e-95)にする。"""
    return "0" if e == 0 else f"{e:.1e}"


display_df = hits_df.head(20).copy()
display_df["identity"] = display_df["identity"].round(2)
display_df["bit_score"] = display_df["bit_score"].round().astype(int)
display_df["evalue"] = display_df["evalue"].apply(_format_evalue)
display_df

12:32:55 [uniprot.entry] Fetching UniProt entry names for 9 accessions ...
12:32:56 [uniprot.entry]   -> 9 entry names resolved

unique candidate proteins (identity >= 40.0%): 9

  accession   entry_name  identity  coverage  align_length   evalue  bit_score
0    Q00526   CDK3_HUMAN     45.28      88.7           307  6.8e-86        261
1    P06493   CDK1_HUMAN     43.10      83.8           290  5.0e-80        246
2    P50613   CDK7_HUMAN     43.14      88.4           306  6.8e-80        247
3    P24941   CDK2_HUMAN     43.77      85.8           297  1.1e-79        245
4    Q00535   CDK5_HUMAN     46.02      83.5           289  5.6e-79        243
5    P21127  CD11B_HUMAN     42.16      88.4           306  3.2e-73        241
6    Q9UQ88  CD11A_HUMAN     41.83      88.4           306  7.3e-73        240
7    P50750   CDK9_HUMAN     40.00      89.6           310  1.2e-68        219
8    O76039  CDKL5_HUMAN     40.00      85.3           295  2.8e-60        207

## 3. 見つかった蛋白ごとにPDBエントリ数・ChEMBL化合物数を集計してランキングする

上位ヒットについて、UniProtのPDB相互参照からPDBエントリ数を、ChEMBLから既知活性化合物数(ユニークな化合物数)を
集計する。両方が揃っている蛋白ほど、この研究(ドッキングテンプレート+SAR参照)で活用しやすいと考えられる。

In [7]:
TOP_N = 40
candidates_df = hits_df.head(TOP_N).copy()

In [9]:
import pickle

import requests
from uniprot.entry import fetch_protein_info
from chembl import local as chembl_local

RANKING_CACHE = OUTDIR / "protein_ranking.csv"
PDB_STRUCTURES_CACHE = OUTDIR / "pdb_structures.pkl"

if RANKING_CACHE.exists() and PDB_STRUCTURES_CACHE.exists():
    print(f"Using cached ranking: {RANKING_CACHE}")
    ranking_df = pd.read_csv(RANKING_CACHE)
    with open(PDB_STRUCTURES_CACHE, "rb") as f:
        pdb_structures_by_accession = pickle.load(f)
else:
    extra_rows = []
    pdb_structures_by_accession = {}
    for _, row in candidates_df.iterrows():
        acc = row["accession"]
        try:
            info = fetch_protein_info(acc)
            pdb_count = len(info["pdb_structures"])
            pdb_structures_by_accession[acc] = info["pdb_structures"]
        except requests.exceptions.RequestException as e:
            print(f"  [skip] {acc}: failed to fetch UniProt info ({e})")
            continue

        chembl_target_id = None
        try:
            chembl_target_id = chembl_local.resolve_target_chembl_id(acc, CHEMBL_DB)
            compounds = chembl_local.fetch_activities(chembl_target_id, CHEMBL_DB)
            compound_count = len({a["molecule_chembl_id"] for a in compounds})
        except ValueError:
            compound_count = 0  # ChEMBL target(SINGLE PROTEIN)が見つからない

        extra_rows.append({
            "accession": acc,
            "pdb_count": pdb_count,
            "chembl_target_id": chembl_target_id,
            "compound_count": compound_count,
        })

    extra_df = pd.DataFrame(extra_rows)
    ranking_df = candidates_df.merge(extra_df, on="accession").sort_values(
        ["pdb_count", "compound_count"], ascending=False
    ).reset_index(drop=True)
    ranking_df.to_csv(RANKING_CACHE, index=False)
    with open(PDB_STRUCTURES_CACHE, "wb") as f:
        pickle.dump(pdb_structures_by_accession, f)
    print(f"Saved ranking to {RANKING_CACHE}")

Using cached ranking: data/cdk20_investigation/protein_ranking.csv

In [16]:
ranking_display_df = ranking_df[
    ["accession", "entry_name", "chembl_target_id", "identity", "coverage",
     "align_length", "evalue", "bit_score", "pdb_count", "compound_count"]
].copy()
ranking_display_df["identity"] = ranking_display_df["identity"].round(2)
ranking_display_df["bit_score"] = ranking_display_df["bit_score"].round().astype(int)
ranking_display_df["evalue"] = ranking_display_df["evalue"].apply(_format_evalue)
ranking_display_df

,accession,entry_name,chembl_target_id,identity,coverage,align_length,evalue,bit_score,pdb_count,compound_count
0,P24941,CDK2_HUMAN,CHEMBL301,43.77,85.8,297,1.1e-79,245,512,2618
1,P50613,CDK7_HUMAN,CHEMBL3055,43.14,88.4,306,6.8e-80,247,53,627
2,P50750,CDK9_HUMAN,CHEMBL3116,40.00,89.6,310,1.2e-68,219,28,1741
3,P06493,CDK1_HUMAN,CHEMBL308,43.10,83.8,290,5.0e-80,246,13,1475
4,Q00535,CDK5_HUMAN,CHEMBL4036,46.02,83.5,289,5.6e-79,243,10,717
5,O76039,CDKL5_HUMAN,CHEMBL1163112,40.00,85.3,295,2.8e-60,207,3,21
6,Q00526,CDK3_HUMAN,CHEMBL4442,45.28,88.7,307,6.8e-86,261,2,47
7,P21127,CD11B_HUMAN,CHEMBL5808,42.16,88.4,306,3.2e-73,241,2,20
8,Q9UQ88,CD11A_HUMAN,CHEMBL5416,41.83,88.4,306,7.3e-73,240,0,48

## 4. 解像度2Å未満のX線構造を一括ダウンロードする

セクション2で集計したPDBエントリのうち、実験手法がX線結晶構造解析(`method == "X-ray"`)かつ
解像度2Å未満のものをすべてダウンロードする。蛋白(entry_name)ごとにサブディレクトリへ保存し、
既にファイルが存在する場合はスキップするので、繰り返し実行しても差分だけ取得される。

In [17]:
from rcsb import fetch_structure
from uniprot.entry import parse_resolution

RESOLUTION_CUTOFF = 2.0
STRUCT_DIR = OUTDIR / "structures"

entry_name_by_accession = candidates_df.set_index("accession")["entry_name"].to_dict()

# (accession, entry_name, pdb_id, resolution) のリストに集約(解像度の良い順)
targets = []
for acc, structures in pdb_structures_by_accession.items():
    for s in structures:
        if s["method"] != "X-ray":
            continue
        res = parse_resolution(s["resolution"])
        if res is None or res >= RESOLUTION_CUTOFF:
            continue
        targets.append((acc, entry_name_by_accession.get(acc, acc), s["id"], res))
targets.sort(key=lambda t: t[3])

total = len(targets)
print(f"X-ray structures with resolution < {RESOLUTION_CUTOFF} A: {total}")

downloaded = 0
skipped = 0
for i, (acc, entry_name, pdb_id, res) in enumerate(targets, start=1):
    subdir = STRUCT_DIR / entry_name
    subdir.mkdir(parents=True, exist_ok=True)
    output = subdir / f"{pdb_id}.cif"
    if output.exists():
        print(f"[{i}/{total}] {entry_name}/{pdb_id}: already exists, skipping")
        skipped += 1
        continue
    print(f"[{i}/{total}] {entry_name}/{pdb_id}: downloading (resolution={res:.2f} A) ...")
    fetch_structure(pdb_id, output)
    downloaded += 1

print(f"Done: {downloaded} downloaded, {skipped} already present, {total} total, saved under {STRUCT_DIR}")

X-ray structures with resolution < 2.0 A: 245
[1/245] CDK2_HUMAN/6Q4G: already exists, skipping
[2/245] CDK2_HUMAN/6Q49: already exists, skipping
[3/245] CDK2_HUMAN/6Q4H: already exists, skipping
[4/245] CDK2_HUMAN/6Q48: already exists, skipping
[5/245] CDK2_HUMAN/6Q4J: already exists, skipping
[6/245] CDK2_HUMAN/6Q4E: already exists, skipping
[7/245] CDK2_HUMAN/6Q4K: already exists, skipping
[8/245] CDK2_HUMAN/6Q4D: already exists, skipping
[9/245] CDK2_HUMAN/6Q3B: already exists, skipping
[10/245] CDK2_HUMAN/6Q4I: already exists, skipping
[11/245] CDK2_HUMAN/6Q4B: already exists, skipping
[12/245] CDK2_HUMAN/6Q4A: already exists, skipping
[13/245] CDK2_HUMAN/9GNO: already exists, skipping
[14/245] CDK2_HUMAN/6Q3F: already exists, skipping
[15/245] CDK2_HUMAN/6Q4F: already exists, skipping
[16/245] CDK2_HUMAN/4EK4: already exists, skipping
[17/245] CDK2_HUMAN/4FKL: already exists, skipping
[18/245] CDK2_HUMAN/2R3I: already exists, skipping
[19/245] CDK2_HUMAN/6Q3C: already exists, skipping
[20/245] CDK2_HUMAN/1GZ8: already exists, skipping
[21/245] CDK2_HUMAN/5MHQ: already exists, skipping
[22/245] CDK2_HUMAN/6GUK: already exists, skipping
[23/245] CDK2_HUMAN/8ERD: already exists, skipping
[24/245] CDK2_HUMAN/4EK3: already exists, skipping
[25/245] CDK2_HUMAN/2R3Q: already exists, skipping
[26/245] CDK2_HUMAN/7RXO: already exists, skipping
[27/245] CDK2_HUMAN/7ZPC: already exists, skipping
[28/245] CDK2_HUMAN/4GCJ: already exists, skipping
[29/245] CDK2_HUMAN/2R3R: already exists, skipping
[30/245] CDK2_HUMAN/4FKU: already exists, skipping
[31/245] CDK2_HUMAN/2R3F: already exists, skipping
[32/245] CDK2_HUMAN/2R3H: already exists, skipping
[33/245] CDK2_HUMAN/6GUH: already exists, skipping
[34/245] CDK2_HUMAN/7RWF: already exists, skipping
[35/245] CDK2_HUMAN/4FKG: already exists, skipping
[36/245] CDK2_HUMAN/8RU8: already exists, skipping
[37/245] CDK2_HUMAN/4EK6: already exists, skipping
[38/245] CDK2_HUMAN/1JVP: already exists, skipping
[39/245] CDK2_HUMAN/7VDU: already exists, skipping
[40/245] CDK2_HUMAN/2R3G: already exists, skipping
[41/245] CDK2_HUMAN/4FKO: already exists, skipping
[42/245] CDK2_HUMAN/4FKS: already exists, skipping
[43/245] CDK2_HUMAN/8UV0: already exists, skipping
[44/245] CDK2_HUMAN/7RWE: already exists, skipping
[45/245] CDK2_HUMAN/7SA0: already exists, skipping
[46/245] CDK2_HUMAN/1H00: already exists, skipping
[47/245] CDK2_HUMAN/1OIT: already exists, skipping
[48/245] CDK2_HUMAN/1URW: already exists, skipping
[49/245] CDK2_HUMAN/3RM6: already exists, skipping
[50/245] CDK2_HUMAN/4EK5: already exists, skipping
[51/245] CDK2_HUMAN/4FKI: already exists, skipping
[52/245] CDK2_HUMAN/4FKP: already exists, skipping
[53/245] CDK2_HUMAN/4FKT: already exists, skipping
[54/245] CDK2_HUMAN/5ANJ: already exists, skipping
[55/245] CDK2_HUMAN/5K4J: already exists, skipping
[56/245] CDK2_HUMAN/5OO0: already exists, skipping
[57/245] CDK2_HUMAN/8FOW: already exists, skipping
[58/245] CDK2_HUMAN/8FP0: already exists, skipping
[59/245] CDK2_HUMAN/9FR2: already exists, skipping
[60/245] CDK2_HUMAN/2R3N: already exists, skipping
[61/245] CDK2_HUMAN/4ACM: already exists, skipping
[62/245] CDK2_HUMAN/4FKJ: already exists, skipping
[63/245] CDK2_HUMAN/4RJ3: already exists, skipping
[64/245] CDK2_HUMAN/7M2F: already exists, skipping
[65/245] CDK2_HUMAN/8ERN: already exists, skipping
[66/245] CDK2_HUMAN/2R3J: already exists, skipping
[67/245] CDK2_HUMAN/2R3L: already exists, skipping
[68/245] CDK2_HUMAN/4EOJ: already exists, skipping
[69/245] CDK2_HUMAN/6YLK: already exists, skipping
[70/245] CDK2_HUMAN/2R3P: already exists, skipping
[71/245] CDK2_HUMAN/5IEY: already exists, skipping
[72/245] CDK2_HUMAN/6YL1: already exists, skipping
[73/245] CDK2_HUMAN/7RA5: already exists, skipping
[74/245] CDK2_HUMAN/2VTT: already exists, skipping
[75/245] CDK2_HUMAN/7S9X: already exists, skipping
[76/245] CDK2_HUMAN/2CCH: already exists, skipping
[77/245] CDK2_HUMAN/2R3K: already exists, skipping
[78/245] CDK2_HUMAN/2R3M: already exists, skipping
[79/245] CDK2_HUMAN/3PXZ: already exists, skipping
[80/245] CDK2_HUMAN/3QQJ: already exists, skipping
[81/245] CDK2_HUMAN/3R73: already exists, skipping
[82/245] CDK2_HUMAN/3RAI: already exists, skipping
[83/245] CDK2_HUMAN/3SW4: already exists, skipping
[84/245] CDK2_HUMAN/4EK8: already exists, skipping
[85/245] CDK2_HUMAN/4FKV: already exists, skipping
[86/245] CDK2_HUMAN/4KD1: already exists, skipping
[87/245] CDK2_HUMAN/5ANE: already exists, skipping
[88/245] CDK2_HUMAN/5ANO: already exists, skipping
[89/245] CDK2_HUMAN/6YL6: already exists, skipping
[90/245] CDK2_HUMAN/7QHL: already exists, skipping
[91/245] CDK2_HUMAN/7S7A: already exists, skipping
[92/245] CDK2_HUMAN/8FP5: already exists, skipping
[93/245] CDK7_HUMAN/8R9A: already exists, skipping
[94/245] CDK2_HUMAN/5OO3: already exists, skipping
[95/245] CDK2_HUMAN/6Q4C: already exists, skipping
[96/245] CDK2_HUMAN/3PY0: already exists, skipping
[97/245] CDK2_HUMAN/3QQF: already exists, skipping
[98/245] CDK2_HUMAN/3QRT: already exists, skipping
[99/245] CDK2_HUMAN/3QWJ: already exists, skipping
[100/245] CDK2_HUMAN/3QX2: already exists, skipping
[101/245] CDK2_HUMAN/3QXO: already exists, skipping
[102/245] CDK2_HUMAN/3QXP: already exists, skipping
[103/245] CDK2_HUMAN/3QZG: already exists, skipping
[104/245] CDK2_HUMAN/3QZI: already exists, skipping
[105/245] CDK2_HUMAN/3R28: already exists, skipping
[106/245] CDK2_HUMAN/3R6X: already exists, skipping
[107/245] CDK2_HUMAN/3R71: already exists, skipping
[108/245] CDK2_HUMAN/3R7U: already exists, skipping
[109/245] CDK2_HUMAN/3R83: already exists, skipping
[110/245] CDK2_HUMAN/3R9N: already exists, skipping
[111/245] CDK2_HUMAN/3RAH: already exists, skipping
[112/245] CDK2_HUMAN/3RAK: already exists, skipping
[113/245] CDK2_HUMAN/3RAL: already exists, skipping
[114/245] CDK2_HUMAN/3RMF: already exists, skipping
[115/245] CDK2_HUMAN/3ROY: already exists, skipping
[116/245] CDK2_HUMAN/3RPO: already exists, skipping
[117/245] CDK2_HUMAN/3RPR: already exists, skipping
[118/245] CDK2_HUMAN/3S1H: already exists, skipping
[119/245] CDK2_HUMAN/4FKQ: already exists, skipping
[120/245] CDK2_HUMAN/6INL: already exists, skipping
[121/245] CDK2_HUMAN/5OSM: already exists, skipping
[122/245] CDK2_HUMAN/3NS9: already exists, skipping
[123/245] CDK2_HUMAN/1H01: already exists, skipping
[124/245] CDK2_HUMAN/1H08: already exists, skipping
[125/245] CDK2_HUMAN/1HCL: already exists, skipping
[126/245] CDK2_HUMAN/1YKR: already exists, skipping
[127/245] CDK2_HUMAN/2C6I: already exists, skipping
[128/245] CDK2_HUMAN/2CLX: already exists, skipping
[129/245] CDK2_HUMAN/2EXM: already exists, skipping
[130/245] CDK2_HUMAN/2R3O: already exists, skipping
[131/245] CDK2_HUMAN/3DDQ: already exists, skipping
[132/245] CDK2_HUMAN/3IG7: already exists, skipping
[133/245] CDK2_HUMAN/3IGG: already exists, skipping
[134/245] CDK2_HUMAN/3PXF: already exists, skipping
[135/245] CDK2_HUMAN/3PXY: already exists, skipping
[136/245] CDK2_HUMAN/3QTQ: already exists, skipping
[137/245] CDK2_HUMAN/3R1S: already exists, skipping
[138/245] CDK2_HUMAN/3R1Y: already exists, skipping
[139/245] CDK2_HUMAN/3R8M: already exists, skipping
[140/245] CDK2_HUMAN/3R8P: already exists, skipping
[141/245] CDK2_HUMAN/3RK7: already exists, skipping
[142/245] CDK2_HUMAN/3RPV: already exists, skipping
[143/245] CDK2_HUMAN/3S00: already exists, skipping
[144/245] CDK2_HUMAN/3SW7: already exists, skipping
[145/245] CDK2_HUMAN/4FKW: already exists, skipping
[146/245] CDK2_HUMAN/5D1J: already exists, skipping
[147/245] CDK2_HUMAN/7ACK: already exists, skipping
[148/245] CDK7_HUMAN/8R99: already exists, skipping
[149/245] CDK2_HUMAN/3QTU: already exists, skipping
[150/245] CDK2_HUMAN/6ATH: already exists, skipping
[151/245] CDK2_HUMAN/8YNG: already exists, skipping
[152/245] CDK2_HUMAN/4BZD: already exists, skipping
[153/245] CDK2_HUMAN/5OSJ: already exists, skipping
[154/245] CDK2_HUMAN/3TIY: already exists, skipping
[155/245] CDK2_HUMAN/7UG1: already exists, skipping
[156/245] CDK2_HUMAN/8VQ3: already exists, skipping
[157/245] CDK2_HUMAN/1E1X: already exists, skipping
[158/245] CDK2_HUMAN/1H07: already exists, skipping
[159/245] CDK2_HUMAN/2B54: already exists, skipping
[160/245] CDK2_HUMAN/2B55: already exists, skipping
[161/245] CDK2_HUMAN/2BTR: already exists, skipping
[162/245] CDK2_HUMAN/2FVD: already exists, skipping
[163/245] CDK2_HUMAN/2VU3: already exists, skipping
[164/245] CDK2_HUMAN/2XNB: already exists, skipping
[165/245] CDK2_HUMAN/3QQL: already exists, skipping
[166/245] CDK2_HUMAN/3QTR: already exists, skipping
[167/245] CDK2_HUMAN/3QTW: already exists, skipping
[168/245] CDK2_HUMAN/3QWK: already exists, skipping
[169/245] CDK2_HUMAN/3R1Q: already exists, skipping
[170/245] CDK2_HUMAN/3R7I: already exists, skipping
[171/245] CDK2_HUMAN/3R8Z: already exists, skipping
[172/245] CDK2_HUMAN/3RJC: already exists, skipping
[173/245] CDK2_HUMAN/3RK9: already exists, skipping
[174/245] CDK2_HUMAN/3RM7: already exists, skipping
[175/245] CDK2_HUMAN/3SQQ: already exists, skipping
[176/245] CDK2_HUMAN/4D1Z: already exists, skipping
[177/245] CDK2_HUMAN/4NJ3: already exists, skipping
[178/245] CDK2_HUMAN/5FP6: already exists, skipping
[179/245] CDK2_HUMAN/3QQK: already exists, skipping
[180/245] CDK2_HUMAN/3QQH: already exists, skipping
[181/245] CDK2_HUMAN/2B52: already exists, skipping
[182/245] CDK2_HUMAN/1H0V: already exists, skipping
[183/245] CDK2_HUMAN/1HCK: already exists, skipping
[184/245] CDK2_HUMAN/2BHE: already exists, skipping
[185/245] CDK2_HUMAN/2C6K: already exists, skipping
[186/245] CDK2_HUMAN/2C6M: already exists, skipping
[187/245] CDK2_HUMAN/2VTH: already exists, skipping
[188/245] CDK2_HUMAN/2VTQ: already exists, skipping
[189/245] CDK2_HUMAN/2VTR: already exists, skipping
[190/245] CDK2_HUMAN/2VTS: already exists, skipping
[191/245] CDK2_HUMAN/2VV9: already exists, skipping
[192/245] CDK2_HUMAN/2W05: already exists, skipping
[193/245] CDK2_HUMAN/2XMY: already exists, skipping
[194/245] CDK2_HUMAN/3EZR: already exists, skipping
[195/245] CDK2_HUMAN/3FZ1: already exists, skipping
[196/245] CDK2_HUMAN/3PXQ: already exists, skipping
[197/245] CDK2_HUMAN/3QL8: already exists, skipping
[198/245] CDK2_HUMAN/3QQG: already exists, skipping
[199/245] CDK2_HUMAN/3QTS: already exists, skipping
[200/245] CDK2_HUMAN/3R7E: already exists, skipping
[201/245] CDK2_HUMAN/3R7Y: already exists, skipping
[202/245] CDK2_HUMAN/3R8L: already exists, skipping
[203/245] CDK2_HUMAN/3R8V: already exists, skipping
[204/245] CDK2_HUMAN/3R9O: already exists, skipping
[205/245] CDK2_HUMAN/3RPY: already exists, skipping
[206/245] CDK2_HUMAN/3RZB: already exists, skipping
[207/245] CDK2_HUMAN/3UNJ: already exists, skipping
[208/245] CDK2_HUMAN/4FKR: already exists, skipping
[209/245] CDK2_HUMAN/5ANG: already exists, skipping
[210/245] CDK2_HUMAN/5ANI: already exists, skipping
[211/245] CDK2_HUMAN/5ANK: already exists, skipping
[212/245] CDK2_HUMAN/8VQ4: already exists, skipping
[213/245] CDK5_HUMAN/4AU8: already exists, skipping
[214/245] CDK2_HUMAN/1OIR: already exists, skipping
[215/245] CDK2_HUMAN/3QHW: already exists, skipping
[216/245] CDK2_HUMAN/7S4T: already exists, skipping
[217/245] CDK2_HUMAN/3QX4: already exists, skipping
[218/245] CDK7_HUMAN/8R9U: already exists, skipping
[219/245] CDK2_HUMAN/5JQ5: already exists, skipping
[220/245] CDK2_HUMAN/5JQ8: already exists, skipping
[221/245] CDK2_HUMAN/1E1V: already exists, skipping
[222/245] CDK2_HUMAN/1PW2: already exists, skipping
[223/245] CDK2_HUMAN/1PXI: already exists, skipping
[224/245] CDK2_HUMAN/2A0C: already exists, skipping
[225/245] CDK2_HUMAN/2C68: already exists, skipping
[226/245] CDK2_HUMAN/3QRU: already exists, skipping
[227/245] CDK2_HUMAN/3QTX: already exists, skipping
[228/245] CDK2_HUMAN/3QU0: already exists, skipping
[229/245] CDK2_HUMAN/3QZH: already exists, skipping
[230/245] CDK2_HUMAN/3R7V: already exists, skipping
[231/245] CDK2_HUMAN/3R9D: already exists, skipping
[232/245] CDK2_HUMAN/3RNI: already exists, skipping
[233/245] CDK2_HUMAN/4BGH: already exists, skipping
[234/245] CDK2_HUMAN/9OB4: already exists, skipping
[235/245] CDK5_HUMAN/3O0G: already exists, skipping
[236/245] CDK2_HUMAN/1JSV: already exists, skipping
[237/245] CDK2_HUMAN/1PXO: already exists, skipping
[238/245] CDK2_HUMAN/3PJ8: already exists, skipping
[239/245] CDK2_HUMAN/7S85: already exists, skipping
[240/245] CDK2_HUMAN/9OB3: already exists, skipping
[241/245] CDK2_HUMAN/2BTS: already exists, skipping
[242/245] CDK2_HUMAN/3EZV: already exists, skipping
[243/245] CDK2_HUMAN/3TI1: already exists, skipping
[244/245] CDK2_HUMAN/4EOP: already exists, skipping
[245/245] CDK2_HUMAN/6GUE: already exists, skipping
Done: 0 downloaded, 245 already present, 245 total, saved under data/cdk20_investigation/structures

## 5. 化合物ごとの活性値(pChEMBL)を集計する

セクション2でランキングした蛋白(ChEMBL targetが見つかったもの)について、ChEMBLの活性データを
化合物(構造標準化済み)×標的蛋白の単位で集計し、pChEMBL値のmedian/mean/standard deviation/個数を求める。
median(代表値) >= 9.0(高活性)の組み合わせだけを抽出する。

In [18]:
from molstd.standardize import standardize_smiles

ACTIVITY_RECORDS_CACHE = OUTDIR / "activity_records.pkl"

if ACTIVITY_RECORDS_CACHE.exists():
    print(f"Using cached activity records: {ACTIVITY_RECORDS_CACHE}")
    with open(ACTIVITY_RECORDS_CACHE, "rb") as f:
        activity_records = pickle.load(f)
else:
    activity_records = []
    targets_with_chembl = ranking_df.dropna(subset=["chembl_target_id"])
    total = len(targets_with_chembl)
    for i, row in enumerate(targets_with_chembl.itertuples(), start=1):
        activities = chembl_local.fetch_activities(row.chembl_target_id, CHEMBL_DB)
        print(f"[{i}/{total}] {row.entry_name} ({row.chembl_target_id}): {len(activities)} activities, standardizing ...")
        n_ok = 0
        for a in activities:
            if a["pchembl_value"] is None or a["canonical_smiles"] is None:
                continue
            std_smiles = standardize_smiles(a["canonical_smiles"])
            if std_smiles is None:
                continue
            activity_records.append({
                "smiles": std_smiles,
                "accession": row.accession,
                "entry_name": row.entry_name,
                "pchembl_value": float(a["pchembl_value"]),
            })
            n_ok += 1
        print(f"    -> {n_ok} usable records")

    with open(ACTIVITY_RECORDS_CACHE, "wb") as f:
        pickle.dump(activity_records, f)
    print(f"Saved {len(activity_records)} activity records to {ACTIVITY_RECORDS_CACHE}")

Using cached activity records: data/cdk20_investigation/activity_records.pkl

In [22]:
PCHEMBL_MEDIAN_CUTOFF = 9.0

activity_records_df = pd.DataFrame(activity_records)
print(f"activity records (standardized SMILES, pChEMBL available): {len(activity_records_df)}")

activity_summary_df = (
    activity_records_df
    .groupby(["smiles", "accession", "entry_name"])["pchembl_value"]
    .agg(median="median", mean="mean", std="std", count="count")
    .reset_index()
    .sort_values("median", ascending=False)
    .reset_index(drop=True)
)
activity_summary_df.to_csv(OUTDIR / "activity_summary.csv", index=False)
print(f"compound x target pairs: {len(activity_summary_df)}")

high_potency_df = activity_summary_df[activity_summary_df["median"] >= PCHEMBL_MEDIAN_CUTOFF].reset_index(drop=True)
high_potency_df.to_csv(OUTDIR / "high_potency_compounds.csv", index=False)
print(f"compound x target pairs with median pChEMBL >= {PCHEMBL_MEDIAN_CUTOFF}: {len(high_potency_df)}")

high_potency_display_df = high_potency_df.copy()
for col in ["median", "mean", "std"]:
    high_potency_display_df[col] = high_potency_display_df[col].round(2)
with pd.option_context("display.max_colwidth", None):
    display(high_potency_display_df)

activity records (standardized SMILES, pChEMBL available): 9194
compound x target pairs: 7293
compound x target pairs with median pChEMBL >= 9.0: 45

,smiles,accession,entry_name,median,mean,std,count
0,COc1ccc(F)cc1-c1cc(NC(=O)Cc2cccnc2)ncn1,P50750,CDK9_HUMAN,10.82,10.82,NaN,1
1,COc1ccc(F)cc1-c1cc(NC(=O)C2CCCNC2)ncn1,P50750,CDK9_HUMAN,10.74,10.74,NaN,1
2,COc1ccc(F)cc1-c1cc(NC(=O)Cc2ccncc2)ncn1,P50750,CDK9_HUMAN,10.54,10.54,NaN,1
3,COc1cccc(F)c1-c1cc(NC(=O)C2CCCNC2)ncn1,P50750,CDK9_HUMAN,10.41,10.41,NaN,1
4,COc1ccccc1-c1cc(NC(=O)C2CCC(=O)NC2)ncn1,P50750,CDK9_HUMAN,10.24,10.24,0.68,2
5,NS(=O)(=O)c1ccc(Nc2ncc(C(F)(F)F)c(Nc3ccc4[nH]cnc4c3)n2)cc1,P06493,CDK1_HUMAN,10.00,10.00,NaN,1
6,COc1ccccc1-c1cc(NC(=O)c2ccc(C)c(NS(C)(=O)=O)c2)ncn1,P50750,CDK9_HUMAN,9.94,9.94,NaN,1
7,CC(C)c1cnn2c(NCc3ccccc3-n3cccn3)nc(OC3CCCNC3)nc12,P50613,CDK7_HUMAN,9.89,9.89,NaN,1
8,O=[N+]([O-])c1cccc(Nc2nccc(-c3cnn4ncccc34)n2)c1,P24941,CDK2_HUMAN,9.52,9.52,NaN,1
9,Cn1ncc(-c2nc(N[C@H]3CC[C@H](N)CC3)ncc2F)c1CC1CC1,P50613,CDK7_HUMAN,9.51,9.51,NaN,1
10,CCc1cnn2c(NCc3ccc[n+]([O-])c3)cc(N3CCCCC3CCO)nc12,Q00535,CDK5_HUMAN,9.50,9.50,NaN,1
11,Clc1cnc(N[C@H]2CCCNC2)nc1-c1c[nH]c2ccccc12,P50613,CDK7_HUMAN,9.48,9.48,0.00,2
12,NS(=O)(=O)c1ccc(Nc2cc(-c3ccc([N+](=O)[O-])cc3)[nH]n2)cc1,P24941,CDK2_HUMAN,9.48,9.48,NaN,1
13,Nc1ccc(-c2cc(Nc3ccc(S(N)(=O)=O)cc3)[nH]n2)cc1,P24941,CDK2_HUMAN,9.47,9.47,NaN,1
14,CC(=O)N1N=C(c2c(O)c3ccccc3oc2=O)CC1c1ccccc1Cl,P06493,CDK1_HUMAN,9.46,9.46,NaN,1
15,CN(C)C/C=C/C(=O)N1CCC(C(=O)Nc2ncc(SCc3ncc(C(C)(C)C)o3)s2)CC1,P50750,CDK9_HUMAN,9.30,9.30,NaN,1
16,CC(=O)NC1CN(c2ccc(Nc3ncc(F)c(-c4cnc(C)n4C(C)C)n3)cc2)C1,P24941,CDK2_HUMAN,9.30,9.30,NaN,1
17,CN1CCC(c2c(O)cc(O)c3c(=O)cc(-c4ccccc4Cl)oc23)C(O)C1,P50750,CDK9_HUMAN,9.20,9.20,0.00,2
18,NC(COc1cncc(-c2ccc3c(c2)C(=Cc2ccc[nH]2)C(=O)N3)c1)Cc1ccccc1,Q00535,CDK5_HUMAN,9.20,9.20,NaN,1
19,CCNCc1cncc(-c2cnc3[nH]nc(-c4nc5cc(F)ccc5[nH]4)c3c2)c1,P06493,CDK1_HUMAN,9.15,9.15,NaN,1
20,CCNCc1cncc(-c2cnc3[nH]nc(-c4nc5cc(OC)ccc5[nH]4)c3c2)c1,P06493,CDK1_HUMAN,9.10,9.10,NaN,1
21,CCc1cnn2c(NCc3ccc[n+]([O-])c3)cc(N3CCCCC3CCO)nc12,P50750,CDK9_HUMAN,9.10,9.10,NaN,1
22,C[C@@H]1CNc2c(sc3ccc4ncccc4c23)C(=O)N1,P06493,CDK1_HUMAN,9.10,9.10,NaN,1
23,CC[C@@H](C)Oc1nc(Nc2ccc(S(N)(=O)=O)cc2)nc(N)c1C=O,P24941,CDK2_HUMAN,9.10,9.10,NaN,1
24,C[C@@]1(O)CCC[C@H]1n1c(=O)c(C(F)F)cc2cnc(NC3CCN(S(C)(=O)=O)CC3)nc21,P24941,CDK2_HUMAN,9.05,9.05,1.41,2
25,C=CC(=O)N1CCc2nc(Nc3ncc(F)c(-c4cc(F)c5nc(C)n(C(C)C)c5c4)n3)ccc2C1,P50750,CDK9_HUMAN,9.04,9.04,0.00,2
26,FC(F)(F)c1cnc(Nc2ccc3[nH]cnc3c2)nc1Nc1ccccc1Cl,P06493,CDK1_HUMAN,9.02,9.02,0.04,2
27,Cc1cnn2c(NCc3ccc[n+]([O-])c3)cc(N3CCCC[C@@H]3CCO)nc12,P24941,CDK2_HUMAN,9.00,9.00,NaN,1
28,Cc1cnn2c(NCc3ccc[n+]([O-])c3)cc(N3CCCC[C@@H]3CCO)nc12,Q00535,CDK5_HUMAN,9.00,9.00,NaN,1
29,NCCCn1nc(C(N)=O)c2c1-c1nc(Nc3ccccc3)ncc1CC2,P24941,CDK2_HUMAN,9.00,9.00,NaN,1
30,CC(C)c1n[nH]c2c(NCc3ccc(-c4ccccn4)cc3)nc(NCC(C)(C)O)nc12,Q00535,CDK5_HUMAN,9.00,9.00,0.00,2
31,CCc1cnn2c(NCc3ccc[n+]([O-])c3)cc(N3CCCC[C@H]3CCO)nc12,Q00535,CDK5_HUMAN,9.00,8.77,0.57,20
32,CCc1cnn2c(NCc3ccc[n+]([O-])c3)cc(C3CCCC[C@H]3CCO)nc12,Q00535,CDK5_HUMAN,9.00,9.00,NaN,1
33,Fc1cc(F)cc(Nc2nccc(-c3cnn4ncccc34)n2)c1,P24941,CDK2_HUMAN,9.00,9.00,NaN,1
34,CCc1cnn2c(NCc3ccc[n+]([O-])c3)cc(C3CCCC[C@H]3CCO)nc12,P24941,CDK2_HUMAN,9.00,9.00,NaN,1
35,CN1CCN(c2cccc(Nc3ncc4c(n3)-c3c(c(C(N)=O)nn3C)CC4)c2)CC1,P24941,CDK2_HUMAN,9.00,9.00,NaN,1
36,Cc1ncc(-c2nc(Nc3ccc(C(=O)NC4CCN(C)CC4)c(F)c3)ncc2F)n1C(C)C,P24941,CDK2_HUMAN,9.00,9.00,NaN,1
37,CCc1cnn2c(NCc3ccc[n+]([O-])c3)cc(N3CCCC[C@@H]3CCO)nc12,Q00535,CDK5_HUMAN,9.00,9.00,NaN,1
38,CCc1cnn2c(NCc3ccc[n+]([O-])c3)cc(N3CCCC[C@@H]3CCO)nc12,P24941,CDK2_HUMAN,9.00,9.00,NaN,1
39,COCCNS(=O)(=O)c1ccc(Nc2nccc(-c3cnc(C)n3C(C)C)n2)cc1,P24941,CDK2_HUMAN,9.00,9.00,NaN,1
40,COCCOCCOCCOCCN(C)S(=O)(=O)c1ccc(N/C=C2\C(=O)Nc3ccc4ncsc4c32)cc1,P24941,CDK2_HUMAN,9.00,9.00,NaN,1
41,CCc1cnn2c(NCc3ccc[n+]([O-])c3)cc(N3CCCC[C@H]3CCO)nc12,P24941,CDK2_HUMAN,9.00,8.73,0.55,24
42,Clc1ccc(Nc2nccc(-c3cnn4ncccc34)n2)cc1Cl,P24941,CDK2_HUMAN,9.00,9.00,NaN,1
43,C[C@@H]1C[C@H]2CN1CCn1nc3c(cccc3c1O)-c1nc3c(cccc3nc1O)O2,P06493,CDK1_HUMAN,9.00,9.00,0.00,2
44,C[C@@H]1CNc2c(sc3ccc4occc4c23)C(=O)N1,P06493,CDK1_HUMAN,9.00,9.00,NaN,1

### 5.1 化合物単位に集約する

同じ化合物(標準化SMILES)が複数の標的蛋白に対して活性データを持つ場合があるため、化合物ごとに
グループ化し、テストされた標的数(`target_count`)・最も高い活性(median pChEMBL)を示した標的の
Entry name(`best_target_entry_name`)・その活性値(`best_pchembl_median`)に集約する。

In [ ]:
from molstd import calc_mol_weight

target_counts = activity_summary_df.groupby("smiles").size().rename("target_count").reset_index()

best_rows = activity_summary_df.loc[activity_summary_df.groupby("smiles")["median"].idxmax()][
    ["smiles", "entry_name", "median"]
].rename(columns={"entry_name": "best_target_entry_name", "median": "best_pchembl_median"})

compound_summary_df = best_rows.merge(target_counts, on="smiles").sort_values(
    "best_pchembl_median", ascending=False
).reset_index(drop=True)
compound_summary_df["mol_weight"] = compound_summary_df["smiles"].apply(calc_mol_weight)
compound_summary_df = compound_summary_df[
    ["smiles", "mol_weight", "best_target_entry_name", "best_pchembl_median", "target_count"]
]
compound_summary_df.to_csv(OUTDIR / "compound_summary.csv", index=False)
print(f"unique compounds: {len(compound_summary_df)}")

MOL_WEIGHT_MIN, MOL_WEIGHT_MAX = 250, 650

high_potency_compound_df = compound_summary_df[
    (compound_summary_df["best_pchembl_median"] >= PCHEMBL_MEDIAN_CUTOFF)
    & (compound_summary_df["mol_weight"] >= MOL_WEIGHT_MIN)
    & (compound_summary_df["mol_weight"] <= MOL_WEIGHT_MAX)
].reset_index(drop=True)
high_potency_compound_df.to_csv(OUTDIR / "high_potency_compound_summary.csv", index=False)
print(
    f"unique compounds with best_pchembl_median >= {PCHEMBL_MEDIAN_CUTOFF} "
    f"and {MOL_WEIGHT_MIN} <= mol_weight <= {MOL_WEIGHT_MAX}: {len(high_potency_compound_df)}"
)

high_potency_compound_display_df = high_potency_compound_df.copy()
high_potency_compound_display_df["best_pchembl_median"] = high_potency_compound_display_df["best_pchembl_median"].round(2)
high_potency_compound_display_df["mol_weight"] = high_potency_compound_display_df["mol_weight"].round(2)

# 表示だけ全行・SMILES非トランケートにする。オプションはこのセル内に限定する
with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
    display(high_potency_compound_display_df)